name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential   # для компиляции (gcc, make и т.д.)
          sudo apt-get install -y clang-format

      - name: Run tests
        run: make run_tests

      - name: Check code formatting
        run: make check_format_all
